/*
 * file "exported.java". DO NOT EDIT MANUALLY. THIS FILE IS GENERATED BY GRADLE.
 */

package xyz.niflheim.exported;

public class Exported {
    /**
     * build.gradle > client > version
     */
    public static String Client_Version = "1.0.0_0";

    /**
     * build.gradle > stockfish > version
     */
    public static String Stockfish_Version = "9";
}