name: Java CI

on: 
  push:
    branches:
      - develop
  pull_request: 
    branches: 
      - master
      - develop         


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: my-tools

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

#    - uses: ./.github/workflows/scripts/copy_engines
#    - name: copy engines
#      working-directory: my-tools
#      shell: bash
#      run: |
#        mkdir assets
#        cd assets
#        mkdir engines
#        cp "${{ github.action_path }}/assets/engines/*" assets/engines

    - name: Build with Gradle
      working-directory: my-tools
      run: ./gradlew build --info
